theme: jekyll-theme-leap-day
layout: default


defaults:
  - scope:
      path: ""
    values:
      layout: default

collections:
  tutorials:
    output: true
    order: 10000
  animations:
    output: true
    order: 10000
  examples:
    output: true
    order: 10000
  generalproperties:
    output: true
    order: 10000
  menu:
    output: true
    order: 10000
  nineslice:
    output: true
    order: 10000